# https://stackoverflow.com/questions/35773299/how-can-you-export-the-visual-studio-code-extension-list
# Downloaded using ```code --list-extensions | xargs -L 1 echo code --install-extension```
code --install-extension asciidoctor.asciidoctor-vscode
code --install-extension atlassian.atlascode
code --install-extension bierner.markdown-mermaid
code --install-extension charliermarsh.ruff
code --install-extension databricks.databricks
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension foam.foam-vscode
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.github-vscode-theme
code --install-extension github.vscode-github-actions
code --install-extension github.vscode-pull-request-github
code --install-extension grapecity.gc-excelviewer
code --install-extension gruntfuggly.todo-tree
code --install-extension jebbs.plantuml
code --install-extension mermaidchart.vscode-mermaid-chart
code --install-extension ms-azuretools.azure-dev
code --install-extension ms-azuretools.vscode-azureappservice
code --install-extension ms-azuretools.vscode-azurecontainerapps
code --install-extension ms-azuretools.vscode-azurefunctions
code --install-extension ms-azuretools.vscode-azureresourcegroups
code --install-extension ms-azuretools.vscode-azurestaticwebapps
code --install-extension ms-azuretools.vscode-azurestorage
code --install-extension ms-azuretools.vscode-azurevirtualmachines
code --install-extension ms-azuretools.vscode-cosmosdb
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.debugpy
code --install-extension ms-python.mypy-type-checker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.vscode-node-azure-pack
code --install-extension njpwerner.autodocstring
code --install-extension pomdtr.excalidraw-editor
code --install-extension randomfractalsinc.vscode-data-table
code --install-extension rangav.vscode-thunder-client
code --install-extension redhat.vscode-yaml
code --install-extension tamasfe.even-better-toml
code --install-extension yzhang.markdown-all-in-one